#!/bin/env/python3
import re
import os
from time import sleep
from selenium import webdriver
#from selenium.common.exceptions import StaleElementReferenceException
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
#from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait
USERNAME_FORM = '/html/body/div[3]/div/div[3]/div/main/div/div[1]/form/div[1]/div[1]/div/div/input'
PASSWORD_FORM = '/html/body/div[3]/div/div[3]/div/main/div/div[1]/form/div[1]/div[2]/div/div/input'
LOGIN_BUTTON = '/html/body/div[3]/div/div[3]/div/main/div/div[1]/form/div[2]/button'
PLACES_LINK = '/html/body/nav[1]/div[1]/div[1]/ul/li[5]/a'

URL = 'https://www.fetlife.com/users/sign_in'
a = 'https://www.fetlife.com'

urls = {
'b' : f'{a}/p',
'c' : f'{a}/p/united-states',
}

selectors = {
    'a' : bot.driver.find_elements(By.XPATH, "//main//div//div//a[@class='link f5 fw7 secondary mr1']"),
    b = [t.text for t in a]
b = [t.get_attribute("href") for t in a]
 id = re.sub('https://fetlife.com/users/', '',b1)


}

chrome_options = Options()
#chrome_options.add_argument('--headless')
chrome_options.add_argument('/home/justin/bin/chromedriver')
bot = webdriver.Chrome(options=chrome_options)
def login():
    ''' login into social media site '''
    bot.get(URL)
    print('got url')
    email_in = bot.find_element(By.XPATH, USERNAME_FORM)
    email_in.send_keys(USERNAME)
    print('entered email')
    pw_in = bot.find_element(By.XPATH, PASSWORD_FORM)
    pw_in.send_keys(PASSWORD)
    print('entered password')
    login_btn = bot.find_element(By.XPATH, LOGIN_BUTTON)
    login_btn.click()
    print('clicked login')

