[options]
    colorscheme = "material"
    filemanager = "nerdtree"
    filetree_direction = "left"
    wrap_line = true
    filetree_direction = 'left'
    relativenumber = true
    default_indent = 4
    expand_tab = true
    search_highlight_persist = false
    automatic_update = true
    vimcompatible = false
[[layers]]
    name = 'autocomplete'
    auto_completion_return_key_behavior = "complete"
    auto_completion_tab_key_behavior = "smart"
[[layers]]
    name = 'shell'
    default_position = 'top'
    default_height = 30
[[layers]]
    name = 'lang#javascript'
    auto_fix = true
    enable_flow_syntax = true
    format_on_save = true
[[layers]]
    name = 'lang#python'
    python_interpreter = '/bin/python3'
    python_file_head = [
      '#!/bin/python3',
]
[[layers]]
    name = 'lsp'
    filetypes = [
        "python",
        "javascript"
    ]
[[layers]]
    name = "format"
    format_on_save = true
[[layers]]
    name = "fzf"
[[layers]]
    name = "lang#vue"
[[layers]]
    name = "edit"
[[layers]]
    name = "tools"
[[layers]]
    name = "ssh"
[[layers]]
    name = "sudo"
[[layers]]
    name = "treesitter"
[[layers]]
    name = "ui"
    enable_sidebar = false
    enable_scrollbar =  false
    enable_indentline = false
    enable_cursorword  = false
    indentline_char = ''
    conceallevel = 0
    concealcursor = ''
    cursorword_delay = 50
    cursorword_exclude_filetype = []
    indentline_exclude_filetyps = []
[[layers]]
    name = 'VersionControl'
