#!/bin/python3
import typer
import pymongo
from constants import my_vars
from getpass import getuser


uri = my_vars["uri"]
client = pymongo.MongoClient(uri)

#users = client["users"]
#test = client["test"]

username = getuser()

def main(dbobj: str, column: bool = False):

    if dbobj == "dbs" and column:
        typer.secho(f"Hello {username} here are your databases",
                    fg=typer.colors.BLUE)
        for database in client.list_database_names():
            typer.secho(database, fg=typer.colors.GREEN)
        return
    elif dbobj == "dbs":
        typer.secho(f"Hello {username} here are your databases",
                    fg=typer.colors.BLUE)
        typer.secho(client.list_database_names(), fg=typer.colors.GREEN)
        return

    if column:
        typer.secho(f"here is your {dbobj} collections {username}",
                    fg=typer.colors.BLUE)
        for collection in client[dbobj].list_collection_names():
            typer.secho(collection, fg=typer.colors.GREEN)
        return

    typer.secho(f"here is your {dbobj} collections {username}",
                fg=typer.colors.BLUE)
    typer.secho(client[dbobj].list_collection_names(), fg=typer.colors.GREEN)


if __name__ == "__main__":
    typer.run(main)
