# SpaceVim Hints


# \ NUMBER = jumps to NUMBER tab
# SPC s c = toggle search_highlight_persist
# SPC t h i =toggle highlight indentation levels
# s t = opens new tab
# s v = opens window below
# s g = opens window to the right
# SPC WINDOWNUMBER = jumps to WINDOWNUMBER



# SPC t t tab manager window

# SPC T m       toggle menu bar
# SPC T t       toggle tool bar

# SPC b N h     create new empty buffer in a new window on the left
# SPC b N j     create new empty buffer in a new window at the bottom
# SPC b N k     create new empty buffer in a new window above
# SPC b N l     create new empty buffer in a new window below
# SPC b N n     create new empty buffer in current window

# SPC f /       Find files with find or fd command
# SPC f b       go to file bookmarks


# SPC f f       open file
# SPC f s       save a file
# SPC f a       save as new file name
# SPC f S       save all files
# SPC f r       open a recent file



# All SpaceVim option below [option] section
[options]
        default_indent = 4
            expand_tab = false
  search_highlight_persist = false
   automatic_update = true
   vimcompatible = false
   colorscheme = "material"
   enable_language_specific_leader = true
   statusline_separator = "arrow"
   statusline_iseparator = "arrow"
   enable_tabline_filetype_icon = true
   enable_statusline_mode = true

    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
#colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit true colors
#enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please install nerd fonts
#   buffer_index_type = 4

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'colorscheme'

[[layers]]
name = "lang#javascript"


[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = "incsearch"

[[layers]]
name = 'denite'
