mkdir Alabama/Cities
mkdir Alaska/Cities
mkdir Arizona/Cities
mkdir Arkansas/Cities
mkdir California/Cities
mkdir Colorado/Cities
mkdir Connecticut/Cities
mkdir Delaware/Cities
mkdir Florida/Cities
mkdir Georgia/Cities
mkdir Hawaii/Cities
mkdir Idaho/Cities
mkdir Illinois/Cities
mkdir Indiana/Cities
mkdir Iowa/Cities
mkdir Kansas/Cities
mkdir Kentucky/Cities
mkdir Louisiana/Cities
mkdir Maine/Cities
mkdir Maryland/Cities
mkdir Massachusetts/Cities
mkdir Michigan/Cities
mkdir Minnesota/Cities
mkdir Mississippi/Cities
mkdir Missouri/Cities
mkdir Montana/Cities
mkdir Nebraska/Cities
mkdir Nevada/Cities
mkdir NewHampshire/Cities
mkdir NewJersey/Cities
mkdir NewMexico/Cities
mkdir NewYork/Cities
mkdir NorthCarolina/Cities
mkdir NorthDakota/Cities
mkdir Ohio/Cities
mkdir Oklahoma/Cities
mkdir Pennsylvania/Cities
mkdir RhodeIsland/Cities
mkdir SouthCarolina/Cities
mkdir SouthDakota/Cities
mkdir Tennessee/Cities
mkdir Texas/Cities
mkdir Vermont/Cities
mkdir Virginia/Cities
mkdir Washington/Cities
mkdir WestVirginia/Cities
mkdir Wisconsin/Cities
mkdir Wyoming/Cities
