rm -rf Alabama/Cities
rm -rf Alaska/Cities
rm -rf Arizona/Cities
rm -rf Arkansas/Cities
rm -rf Colorado/Cities
rm -rf Connecticut/Cities
rm -rf Delaware/Cities
rm -rf Florida/Cities
rm -rf Georgia/Cities
rm -rf Hawaii/Cities
rm -rf Idaho/Cities
rm -rf Illinois/Cities
rm -rf Indiana/Cities
rm -rf Iowa/Cities
rm -rf Kansas/Cities
rm -rf Kentucky/Cities
rm -rf Louisiana/Cities
rm -rf Maine/Cities
rm -rf Maryland/Cities
rm -rf Massachusetts/Cities
rm -rf Michigan/Cities
rm -rf Minnesota/Cities
rm -rf Mississippi/Cities
rm -rf Missouri/Cities
rm -rf Montana/Cities
rm -rf Nebraska/Cities
rm -rf Nevada/Cities
rm -rf NewHampshire/Cities
rm -rf NewJersey/Cities
rm -rf NewMexico/Cities
rm -rf NewYork/Cities
rm -rf NorthCarolina/Cities
rm -rf NorthDakota/Cities
rm -rf Ohio/Cities
rm -rf Oklahoma/Cities
rm -rf Pennsylvania/Cities
rm -rf RhodeIsland/Cities
rm -rf SouthCarolina/Cities
rm -rf SouthDakota/Cities
rm -rf Tennessee/Cities
rm -rf Texas/Cities
rm -rf Vermont/Cities
rm -rf Virginia/Cities
rm -rf Washington/Cities
rm -rf WestVirginia/Cities
rm -rf Wisconsin/Cities
rm -rf Wyoming/Cities
