rm -rf Alabama/getLoveUsersv8.py
rm -rf Alaska/getLoveUsersv8.py
rm -rf Arizona/getLoveUsersv8.py
rm -rf Arkansas/getLoveUsersv8.py
rm -rf Colorado/getLoveUsersv8.py
rm -rf Connecticut/getLoveUsersv8.py
rm -rf Delaware/getLoveUsersv8.py
rm -rf Florida/getLoveUsersv8.py
rm -rf Georgia/getLoveUsersv8.py
rm -rf Hawaii/getLoveUsersv8.py
rm -rf Idaho/getLoveUsersv8.py
rm -rf Illinois/getLoveUsersv8.py
rm -rf Indiana/getLoveUsersv8.py
rm -rf Iowa/getLoveUsersv8.py
rm -rf Kansas/getLoveUsersv8.py
rm -rf Kentucky/getLoveUsersv8.py
rm -rf Louisiana/getLoveUsersv8.py
rm -rf Maine/getLoveUsersv8.py
rm -rf Maryland/getLoveUsersv8.py
rm -rf Massachusetts/getLoveUsersv8.py
rm -rf Michigan/getLoveUsersv8.py
rm -rf Minnesota/getLoveUsersv8.py
rm -rf Mississippi/getLoveUsersv8.py
rm -rf Missouri/getLoveUsersv8.py
rm -rf Montana/getLoveUsersv8.py
rm -rf Nebraska/getLoveUsersv8.py
rm -rf Nevada/getLoveUsersv8.py
rm -rf NewHampshire/getLoveUsersv8.py
rm -rf NewJersey/getLoveUsersv8.py
rm -rf NewMexico/getLoveUsersv8.py
rm -rf NewYork/getLoveUsersv8.py
rm -rf NorthCarolina/getLoveUsersv8.py
rm -rf NorthDakota/getLoveUsersv8.py
rm -rf Ohio/getLoveUsersv8.py
rm -rf Oklahoma/getLoveUsersv8.py
rm -rf Pennsylvania/getLoveUsersv8.py
rm -rf RhodeIsland/getLoveUsersv8.py
rm -rf SouthCarolina/getLoveUsersv8.py
rm -rf SouthDakota/getLoveUsersv8.py
rm -rf Tennessee/getLoveUsersv8.py
rm -rf Texas/getLoveUsersv8.py
rm -rf Vermont/getLoveUsersv8.py
rm -rf Virginia/getLoveUsersv8.py
rm -rf Washington/getLoveUsersv8.py
rm -rf WestVirginia/getLoveUsersv8.py
rm -rf Wisconsin/getLoveUsersv8.py
rm -rf Wyoming/getLoveUsersv8.py
