rm States/Alabama/getLoveUsersv8.py
rm States/Alaska/getLoveUsersv8.py
rm States/Arizona/getLoveUsersv8.py
rm States/Arkansas/getLoveUsersv8.py
rm States/California/getLoveUsersv8.py
rm States/Colorado/getLoveUsersv8.py
rm States/Connecticut/getLoveUsersv8.py
rm States/Delaware/getLoveUsersv8.py
rm States/Florida/getLoveUsersv8.py
rm States/Georgia/getLoveUsersv8.py
rm States/Hawaii/getLoveUsersv8.py
rm States/Idaho/getLoveUsersv8.py
rm States/Illinois/getLoveUsersv8.py
rm States/Indiana/getLoveUsersv8.py
rm States/Iowa/getLoveUsersv8.py
rm States/Kansas/getLoveUsersv8.py
rm States/Kentucky/getLoveUsersv8.py
rm States/Louisiana/getLoveUsersv8.py
rm States/Maine/getLoveUsersv8.py
rm States/Maryland/getLoveUsersv8.py
rm States/Massachusetts/getLoveUsersv8.py
rm States/Michigan/getLoveUsersv8.py
rm States/Minnesota/getLoveUsersv8.py
rm States/Mississippi/getLoveUsersv8.py
rm States/Missouri/getLoveUsersv8.py
rm States/Montana/getLoveUsersv8.py
rm States/Nebraska/getLoveUsersv8.py
rm States/Nevada/getLoveUsersv8.py
rm States/NewHampshire/getLoveUsersv8.py
rm States/NewJersey/getLoveUsersv8.py
rm States/NewMexico/getLoveUsersv8.py
rm States/NewYork/getLoveUsersv8.py
rm States/NorthCarolina/getLoveUsersv8.py
rm States/NorthDakota/getLoveUsersv8.py
rm States/Ohio/getLoveUsersv8.py
rm States/Oklahoma/getLoveUsersv8.py
rm States/Oregon/getLoveUsersv8.py
rm States/Pennsylvania/getLoveUsersv8.py
rm States/RhodeIsland/getLoveUsersv8.py
rm States/SouthCarolina/getLoveUsersv8.py
rm States/SouthDakota/getLoveUsersv8.py
rm States/Tennessee/getLoveUsersv8.py
rm States/Texas/getLoveUsersv8.py
rm States/Utah/getLoveUsersv8.py
rm States/Vermont/getLoveUsersv8.py
rm States/Virginia/getLoveUsersv8.py
rm States/Washington/getLoveUsersv8.py
rm States/WestVirginia/getLoveUsersv8.py
rm States/Wisconsin/getLoveUsersv8.py
rm States/Wyoming/getLoveUsersv8.py
