alias br="nvim ~/.bashrc; bash"
alias ba="nvim ~/.bash_aliases; bash"
alias bf="nvim ~/.bash_functions; bash"
alias findtext="ftext"
alias c='clear'
alias l='ls -1'
alias la='ls -1a'
alias g='git'
alias m='mv'
alias py="python3"
alias v='nvim'
alias vi='nvim'
alias vim='nvim'
alias vr='nvim ~/.SpaceVim.d/init.toml'
alias vimconfig='nvim ~/.SpaceVim.d/init.toml'
alias R="rm -rf"
alias R="rm -rf"
alias db="mysql -u root -p"

# Alias's to change the directory
alias web='cd /var/www/html'
alias desk='cdls ~/Desktop'
alias downloads='cdls ~/Downloads'
alias docs='cdls ~/Documents'
alias pics='cdls ~/Pictures'
alias bin='cdls ~/bin'
alias configs='cdls ~/Desktop/configuration-files'
alias cheats='cdls ~/Desktop/cheat-sheets'
alias online='cdls ~/Desktop/online-presence-management'

alias cpu="grep 'cpu ' /proc/stat | awk '{usage=(\$2+\$4)*100/(\$2+\$4+\$5)} END {print usage}' | awk '{printf(\"%.1f\n\", \$1)}'"
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Show help for this .bashrc file
#alias bashhelp='less ~/.bashrc_help'

# a to show the date
alias showdate='date "+%Y-%m-%d %A %T %Z"'

# Alias's to modified commands
alias cp='cp -i'
alias cpf='\cp'
alias mv='mv -i'
alias mvf='\mv'
alias rm='rm -iv'
alias rmf='\rm'
alias mkdir='mkdir -p'
alias ps='ps auxf'
alias ping='ping -c 10'
alias less='less -R'
#alias cls='clear'
alias apt-get='sudo apt-get'
alias apt='sudo apt'
alias multitail='multitail --no-repeat -c'

#alias svi='sudo vim'
#alias vis='vim "+set si"'

# Change directory aes
#alias home='cd ~'
#alias cd..='cd ..'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'

# cd into the old directory
alias bd='cd "$OLDPWD"'

# Remove a directory and all files
alias rmd='/bin/rm  --recursive --force --verbose '

# Alias's for multiple directory listing commands
alias la='ls -Alh' # show hidden files
alias ls='ls -aFh --color=always' # add colors and file type extensions
alias lx='ls -lXBh' # sort by extension
alias grep="/usr/bin/grep $GREP_OPTIONS"
unset GREP_OPTIONS
alias lk='ls -lSrh' # sort by size
alias lc='ls -lcrh' # sort by change time
alias lu='ls -lurh' # sort by access time
alias lr='ls -lRh' # recursive ls
alias lt='ls -ltrh' # sort by date
alias lm='ls -alh |more' # pipe through 'more'
alias lw='ls -xAh' # wide listing format
alias ll='ls -Fls' # long listing format
alias labc='ls -lap' #alphabetical sort
alias lf="ls -l | egrep -v '^d'" # files only
alias ldir="ls -l | egrep '^d'" # directories only

# a chmod commands
alias mx='chmod a+x'
alias 000='chmod -R 000'
alias 644='chmod -R 644'
alias 666='chmod -R 666'
alias 755='chmod -R 755'
alias 777='chmod -R 777'

# Search command line history
alias h="history | grep "

# Search running processes
alias proccesses="ps aux | grep "
alias topcpu="/bin/ps -eo pcpu,pid,user,args | sort -k 1 -r | head -10"

# Search files in the current folder
alias f="find . | grep "

# Count all files (recursively) in the current folder
alias countfiles="for t in files links directories; do echo \`find . -type \${t:0:1} | wc -l\` \$t; done 2> /dev/null"

# To see if a command is aed, a file, or a built-in command
alias checkcommand="type -t"

# Show current network connections to the server
alias ipview="netstat -anpl | grep :80 | awk {'print \$5'} | cut -d\":\" -f1 | sort | uniq -c | sort -n | sed -e 's/^ *//' -e 's/ *\$//'"

# Show open ports
alias openports='netstat -nape --inet'

# Alias's for safe and forced reboots
alias rebootsafe='sudo shutdown -r now'
alias rebootforce='sudo shutdown -r -n now'

# Alias's to show disk space and space used in a folder
alias diskspace="du -S | sort -n -r |more"
alias folders='du -h --max-depth=1'
alias folderssort='find . -maxdepth 1 -type d -print0 | xargs -0 du -sk | sort -rn'
alias tree='tree -CAhF --dirsfirst'
alias treed='tree -CAFd'
alias mountedinfo='df -hT'

# Alias's for archives
alias mktar='tar -cvf'
alias mkbz2='tar -cvjf'
alias mkgz='tar -cvzf'
alias untar='tar -xvf'
alias unbz2='tar -xvjf'
alias ungz='tar -xvzf'

# Show all logs in /var/log
alias logs="sudo find /var/log -type f -exec file {} \; | grep 'text' | cut -d' ' -f1 | sed -e's/:$//g' | grep -v '[0-9]$' | xargs tail -f"

# SHA1
alias sha1='openssl sha1'
